Repository Back-Country-Buddy/backcountry-buddy-UI, pull requests merged in 2021-04, with the labels that each got.

#29 Feat/initial setup
  package-lock.json
  package.json
  src/App.js
  src/UserDummyData.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.css
  src/components/Form/Debrief.tsx
  src/components/Form/Form.css
  src/components/Form/Plan.tsx
  src/components/Form/Ride.tsx
  src/components/Form/TourForm.tsx
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.tsx
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTourDetails.tsx
  src/components/PastTours/PastTours.css
  src/components/PastTours/PastTours.tsx
  src/components/PastTours/SearchBar.tsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.tsx
  src/index.js
  src/react-app-env.d.ts
  tsconfig.json
Labels: FE

#51 Add service worker files and test it with lighthouse
  package-lock.json
  public/index.html
  public/runRegistration.js
  public/sw.js
  src/index.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: FE

#59 Styling/enhancements
  public/index.html
  src/assets/archcloud.png
  src/assets/arrow.png
  src/assets/bluepurplejagged.png
  src/assets/brightpurple.png
  src/assets/cartoonmtn.jpeg
  src/assets/l19mq2nvmrb21n9t6caol5a3i4-e0accceffe51d5a200528c5b0363b929.png
  src/assets/lightpurple.png
  src/assets/lightpurple2.png
  src/assets/orangecloud.png
  src/assets/pinkclouds.png
  src/assets/purpblue.png
  src/assets/purplebluecircle.png
  src/assets/skibum.png
  src/assets/snow-winter-sport-piste-landscape-snow-5f27a0621b15f63c01da5fa84ac950b1.png
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.css
  src/components/CurrentTours/CurrentTours.tsx
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.tsx
  src/components/Login/LoginButton.js
  src/components/Login/buttons.css
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTourDetails.tsx
  src/components/PastTours/PastTours.css
  src/components/PastTours/PastTours.tsx
  src/components/PastTours/SearchBar.tsx
  src/index.css
Labels: FE, enhancement

#64 Feat/api calls
  cypress/integration/current_tours_spec.js
  cypress/integration/form_spec.js
  cypress/integration/landing_spec.js
  cypress/integration/profile_spec.js
  public/runRegistration.js
  public/sw.js
  src/assets/darkpurplemtn.png
  src/components/App/App.js
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.tsx
  src/components/Form/Debrief.tsx
  src/components/Form/Form.css
  src/components/Form/Plan.tsx
  src/components/Form/TourForm.tsx
  src/components/LandingPage/LandingPage.tsx
  src/components/Login/LogoutButton.js
  src/components/PastTours/PastTours.tsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.tsx
  src/index.js
  src/mockdata/UserDummyData.js
  src/util.js
  src/util.tsx
Labels: FE

#82 Feat/api pasttours
  src/components/App/App.js
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.tsx
  src/components/Form/Debrief.tsx
  src/components/Form/TourForm.tsx
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTourDetails.tsx
  src/components/PastTours/PastTours.tsx
  src/util.js
Labels: FE

#87 Feat/delete tour
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.tsx
  src/components/Form/TourForm.tsx
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTours.css
  src/components/PastTours/PastTours.tsx
  src/util.js
Labels: FE

#90 Feat/create tour
  src/assets/departureCheck.png
  src/components/App/App.js
  src/components/Form/Ride.tsx
  src/components/Form/TourForm.tsx
  src/components/LandingPage/LandingPage.tsx
  src/components/PastTours/PastTours.tsx
  src/util.js
Labels: FE, enhancement

#89 Styling/final updates
  src/assets/icons8-search-30.png
  src/assets/ride-diagram.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.css
  src/components/CurrentTours/CurrentTours.tsx
  src/components/Form/Debrief.tsx
  src/components/Form/Form.css
  src/components/Form/FormNav.js
  src/components/Form/Plan.tsx
  src/components/Form/Ride.tsx
  src/components/Form/SectionTitle.tsx
  src/components/Form/TextField.tsx
  src/components/Form/TourForm.tsx
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.tsx
  src/components/Login/LoginButton.js
  src/components/Login/LogoutButton.js
  src/components/Login/buttons.css
  src/components/NavBar/NavBar.tsx
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTourDetails.tsx
  src/components/PastTours/PastTours.css
  src/components/PastTours/PastTours.tsx
  src/components/PastTours/SearchBar.tsx
  src/components/Profile/Profile.css
  src/components/Profile/Profile.tsx
  src/util.js
  tsconfig.json
Labels: FE

#94 Feat/api refactor
  .travis.yml
  package-lock.json
  package.json
  src/apiRequests/dataCleaners.js
  src/apiRequests/header.js
  src/apiRequests/planRequests.js
  src/apiRequests/promiseHandling.js
  src/apiRequests/tourRequests.js
  src/apiRequests/userRequests.js
  src/assets/buddy.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/CurrentTours/CurrentTours.tsx
  src/components/Error/Error.js
  src/components/Form/TourForm.tsx
  src/components/Loader/Loader.js
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTourDetails.tsx
  src/components/PastTours/PastTours.tsx
  src/components/Profile/Profile.tsx
  src/mockdata/CurrentToursDummyData.js
  src/mockdata/PastTourData.js
  src/mockdata/UserDummyData.js
  src/mockdata/tourPlan.tsx
  tsconfig.json
Labels: FE

#96 Fix/api refactor
  .travis.yml
  src/components/Form/Plan.tsx
  src/components/PastTours/PastTours.tsx
  src/components/PastTours/SearchBar.tsx
Labels: FE

#101 Styling/responsive design
  src/assets/archcloud.png
  src/assets/arrow.png
  src/assets/cartoonmtn.jpeg
  src/assets/darkpurplemtn.png
  src/assets/departureCheck.png
  src/assets/landing.jpeg
  src/assets/lightpurple2.png
  src/assets/orangecloud.png
  src/assets/placeholderChartAsset.png
  src/assets/skibum.png
  src/assets/snow-winter-sport-piste-landscape-snow-5f27a0621b15f63c01da5fa84ac950b1.png
  src/components/App/App.css
  src/components/CurrentTours/CurrentTourCard.tsx
  src/components/Form/Form.css
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.tsx
  src/components/PastTours/PastTourCard.tsx
  src/components/PastTours/PastTours.css
  src/components/Profile/Profile.css
  tsconfig.json
Labels: FE

#102 Fix/misc
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/runRegistration.js
  public/sw.js
  src/index.js
  src/reportWebVitals.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
  src/util.js
Labels: FE

#104 Feat/add friends
  src/apiRequests/dataCleaners.js
  src/apiRequests/promiseHandling.js
  src/apiRequests/tourRequests.js
  src/components/App/App.js
  src/components/Form/Plan.tsx
  src/components/Form/TourForm.tsx
  src/index.js
  tsconfig.json
Labels: FE

#108 Fix/mobile styling
  src/apiRequests/dataCleaners.js
  src/apiRequests/header.js
  src/apiRequests/planRequests.js
  src/apiRequests/promiseHandling.js
  src/apiRequests/tourRequests.js
  src/apiRequests/userRequests.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/CurrentTours/CurrentTours.tsx
  src/components/Form/Form.css
  src/components/Form/Plan.tsx
  src/components/Form/Ride.tsx
  src/components/Form/SectionTitle.tsx
  src/components/Form/TourForm.tsx
  src/components/NavBar/NavBar.css
  src/components/PastTours/PastTourDetails.tsx
  src/components/PastTours/PastTours.css
  src/components/PastTours/PastTours.tsx
  src/components/PastTours/SearchBar.tsx
Labels: FE

#109 Testing/tours
  .travis.yml
  cypress/fixtures/currentTours.json
  cypress/integration/create_tour_spec.js
  cypress/integration/current_tours_spec.js
  cypress/integration/form_spec.js
  cypress/integration/landing_spec.js
  cypress/integration/profile_spec.js
  src/components/Profile/Profile.tsx
Labels: FE

#110 Create readme draft
  README.md
Labels: FE, documentation
